### ISSUE TITLE
Doesn't show if the Sub language is English (United States)

### ISSUE THREAD

**Issue by reazonozaer** [ayancey/YoutubeSubtitlePreview#1]
Just as the title says. If the subtitles language is shown as _English (United States)_ instead of just _English_ then no symbol is shown on the thumbnail.

**Comment by ayancey** [comment]
Can you please link an example video?

**Comment by reazonozaer** [comment]
Here's the first video I noticed it on. https://www.youtube.com/watch?v=pwXhX9KVrew 
If you look at the subtitles choices it is written as English (United States)

I fixed it by changing line 41 to:
if ((text.includes('lang_code="' + TARGET_LANGUAGE + '"')) || (text.includes('lang_code="' + TARGET_LANGUAGE + '-US"')))

I took a course in javascript like years ago, but between what I remembered and looking up a couple things I was able to make that rough patch.
